### PR TITLE
chore: publish PRs in Surge.sh. Fixes #1195

### LINKED ISSUE #1195: Improve PRs xp
It would be nice to auto-deploy:
- a mock version of the app
- the storybook

and have a coverage report like this:
image

### PR DESCRIPTION
**Pull request by gastaldi**

### CODE REVIEW

**Comment by fabric8cd** [comment]
Launcher Frontend preview: https://1196-pr-launcher-frontend-fabric8-launcher.surge.sh

**Comment by fabric8cd** [comment]
Launcher Frontend preview: https://1196-pr-launcher-frontend-fabric8-launcher.surge.sh

**Comment by gastaldi** [comment]
The only problem is that the surge.sh URL is never teardown. Ideally it should be possible to listen for when the PR is closed and delete the deployed project by following the steps in https://surge.sh/help/tearing-down-a-project

**Comment by fabric8cd** [comment]
Launcher Frontend preview: https://1196-pr-app-launcher-frontend-fabric8-launcher.surge.sh

**Comment by fabric8cd** [comment]
Storybook preview: https://1196-pr-storybook-launcher-frontend-fabric8-launcher.surge.sh

**Comment by fabric8cd** [comment]
Launcher Frontend preview: https://1196-pr-app-launcher-frontend-fabric8-launcher.surge.sh

**Comment by fabric8cd** [comment]
Storybook preview: https://1196-pr-storybook-launcher-frontend-fabric8-launcher.surge.sh

**Pull request merged**
