### PR TITLE
WIP ngx-forge ui

### PR DESCRIPTION
**Pull request by edewit**
Initial integration of the [ngx-launcher](https://github.com/fabric8-launcher/ngx-launcher) project, still needs some work on the ngx-launcher before this can work

### CODE REVIEW

**Comment by quintesse** [comment]
What do I have to do to take a look at this @edewit ?

**Comment by edewit** [comment]
sure @quintesse have a look

**Comment by quintesse** [comment]
I meant: "how?" :)
What url do I go to test it?
Or does it replace the existing UI?

**Comment by edewit** [comment]
@quintesse this removes the old UI that we had and replaces it with the one from ngx-launcher all you have to do is execute `./run.sh` and go to `http://localhost:8088/`

**Comment by edewit** [comment]
closed in favor of #246

**Pull request closed without merging**
