### PR TITLE
fix: create a warning when project already exists

### PR DESCRIPTION
**Pull request by edewit**

### CODE REVIEW

**Comment by fabric8cd** [comment]
This PR was deployed **with mocked data** in the following URLs for your appreciation:
- Frontend: https://fabric8-launcher-frontend-pr-1292-app.surge.sh
- Welcome App: https://fabric8-launcher-frontend-pr-1292-welcome-app.surge.sh
- Storybook: https://fabric8-launcher-frontend-pr-1292-storybook.surge.sh

**Comment by edewit** [comment]
Screenshot from 2019-05-03 15-11-36

**Comment by gastaldi** [comment]
According to https://docs.openshift.com/container-platform/3.11/architecture/core_concepts/projects_and_users.html there isn't an owner concept in Projects, just roles that the user has on it., So I think the warning message needs some thought

**Comment by edewit** [comment]
@gastaldi what I mean is that you can only continue if the project is yours, or am I wrong? If you had something else in mind, I'm happy to change it to that

**Comment by gastaldi** [comment]
AFAIK You must have the admin role in the project to be able to modify it.
That role is added when you create the project but can also be assigned to
anyone using `oc adm` commands

Em Sex, 3 de mai de 2019 10:37, Erik Jan de Wit <notifications@github.com>
escreveu:

**Pull request merged**
