### PR TITLE
refactor: remove launcher-app and launcher-welcome-app (moved to main…

### PR DESCRIPTION
**Pull request by ia3andy**
… repo)

### CODE REVIEW

**Comment by gastaldi** [comment]
Don't merge this until the creator is merged in the launcher-backend repository and the template is configured to use the launcher-backend as the single service

**Comment by fabric8cd** [comment]
This PR was deployed **with mocked data** in the following URLs for your appreciation:
- Storybook: https://fabric8-launcher-frontend-pr-1311-storybook.surge.sh

**Comment by gastaldi** [comment]
@ia3andy go ahead and merge this PR

**Comment by ia3andy** [comment]
@gastaldi I'll do that when I have time ok ;-) I need to rebase it first since the last changes..

**Pull request merged**
